id = "Authzed"
name = "Authzed Spicedb"
description = "Language support for Authzed Spicedb"
version = "0.1.0"
schema_version = 1
repository = "https://github.com/zed-extensions/authzed"
authors = ["mleonidas"]

[grammars.authzed]
repository = "https://github.com/mleonidas/tree-sitter-authzed"
commit = "1dec7e1af96c56924e3322cd85fdce15d0a31d00"
